# Generated by Django 3.2.7 on 2023-01-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
