# Generated by Django 3.2.7 on 2023-01-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20230102_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={},
        ),
        migrations.AlterModelManagers(
            name='solution',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='solution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='name',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='visible',
        ),
    ]
