# Generated by Django 3.2.7 on 2023-01-03 17:51

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_userlibrary'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userlibrary',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
