# Generated by Django 3.2.7 on 2023-01-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_rename_stripe_charge_id_payment_flutterwave_charge_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='flutterwave_charge_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
